/* 中学1年生のための５分英単語 — 中1教科書の基本語を網羅 */
const UNITS = [
  { id: "greetings", name: "あいさつ", blurb: "毎日つかうことば" },
  { id: "people", name: "自分と相手", blurb: "I / you / he / she" },
  { id: "school", name: "学校と教科", blurb: "教室・教科のことば" },
  { id: "numbers", name: "数字と年齢", blurb: "How old are you?" },
  { id: "family", name: "家族", blurb: "my family" },
  { id: "wh", name: "疑問詞", blurb: "what / where / who" },
  { id: "weather", name: "天気と季節", blurb: "きょうの天気" },
  { id: "feelings", name: "気分とようす", blurb: "happy / tired / hungry" },
  { id: "around", name: "身のまわり", blurb: "this / that / 動物" },
  { id: "colors", name: "色", blurb: "What color?" },
  { id: "food", name: "食べ物", blurb: "I like apples." },
  { id: "sports", name: "スポーツ", blurb: "play soccer" },
  { id: "actions", name: "動作", blurb: "play / study / go" },
  { id: "can", name: "できること", blurb: "I can swim." },
  { id: "time", name: "曜日と時間", blurb: "today / Sunday" },
  { id: "months", name: "月", blurb: "January 〜 December" },
  { id: "places", name: "場所", blurb: "park / station" },
  { id: "adjectives", name: "形容詞", blurb: "big / new / favorite" },
];

const WORDS = [
  // あいさつ
  { id: "hello", unit: "greetings", en: "Hello", ja: "こんにちは", exampleEn: "Hello, I'm Yumi.", exampleJa: "こんにちは、ユミです。" },
  { id: "hi", unit: "greetings", en: "Hi", ja: "やあ、こんにちは", exampleEn: "Hi, Ken.", exampleJa: "やあ、ケン。" },
  { id: "thank-you", unit: "greetings", en: "Thank you", ja: "ありがとう", exampleEn: "Thank you very much.", exampleJa: "どうもありがとう。" },
  { id: "thanks", unit: "greetings", en: "Thanks", ja: "ありがとう（くだけた）", exampleEn: "Thanks a lot.", exampleJa: "どうも。" },
  { id: "youre-welcome", unit: "greetings", en: "You're welcome", ja: "どういたしまして", exampleEn: "You're welcome.", exampleJa: "どういたしまして。" },
  { id: "excuse-me", unit: "greetings", en: "Excuse me", ja: "すみません", exampleEn: "Excuse me.", exampleJa: "すみません。" },
  { id: "im-sorry", unit: "greetings", en: "I'm sorry", ja: "ごめんなさい", exampleEn: "I'm sorry.", exampleJa: "ごめんなさい。" },
  { id: "good-morning", unit: "greetings", en: "Good morning", ja: "おはよう", exampleEn: "Good morning, everyone.", exampleJa: "みなさん、おはよう。" },
  { id: "good-afternoon", unit: "greetings", en: "Good afternoon", ja: "こんにちは（午後）", exampleEn: "Good afternoon.", exampleJa: "こんにちは。" },
  { id: "good-evening", unit: "greetings", en: "Good evening", ja: "こんばんは", exampleEn: "Good evening.", exampleJa: "こんばんは。" },
  { id: "good-night", unit: "greetings", en: "Good night", ja: "おやすみなさい", exampleEn: "Good night.", exampleJa: "おやすみなさい。" },
  { id: "nice-to-meet-you", unit: "greetings", en: "Nice to meet you", ja: "はじめまして", exampleEn: "Nice to meet you.", exampleJa: "はじめまして。" },
  { id: "how-are-you", unit: "greetings", en: "How are you?", ja: "お元気ですか", exampleEn: "How are you?", exampleJa: "げんきですか。" },
  { id: "fine", unit: "greetings", en: "fine", ja: "元気な", exampleEn: "I'm fine, thank you.", exampleJa: "元気です、ありがとう。" },
  { id: "please", unit: "greetings", en: "Please", ja: "お願いします", exampleEn: "Please sit down.", exampleJa: "すわってください。" },
  { id: "yes", unit: "greetings", en: "yes", ja: "はい", exampleEn: "Yes, I am.", exampleJa: "はい、そうです。" },
  { id: "no", unit: "greetings", en: "no", ja: "いいえ", exampleEn: "No, I'm not.", exampleJa: "いいえ、ちがいます。" },
  { id: "ok", unit: "greetings", en: "OK", ja: "わかった、いいよ", exampleEn: "OK, let's go.", exampleJa: "わかった、行こう。" },
  { id: "goodbye", unit: "greetings", en: "Goodbye", ja: "さようなら", exampleEn: "Goodbye, everyone.", exampleJa: "みなさん、さようなら。" },
  { id: "bye", unit: "greetings", en: "Bye", ja: "じゃあね", exampleEn: "Bye, Ken.", exampleJa: "じゃあね、ケン。" },
  { id: "see-you", unit: "greetings", en: "See you", ja: "またね", exampleEn: "See you tomorrow.", exampleJa: "またあした。" },

  // 自分と相手
  { id: "i", unit: "people", en: "I", ja: "私は", exampleEn: "I am a student.", exampleJa: "私は生徒です。" },
  { id: "my", unit: "people", en: "my", ja: "私の", exampleEn: "This is my book.", exampleJa: "これは私の本です。" },
  { id: "me", unit: "people", en: "me", ja: "私を・私に", exampleEn: "Look at me.", exampleJa: "私を見て。" },
  { id: "mine", unit: "people", en: "mine", ja: "私のもの", exampleEn: "This is mine.", exampleJa: "これは私のものです。" },
  { id: "you", unit: "people", en: "you", ja: "あなたは", exampleEn: "You are my friend.", exampleJa: "あなたは友だちです。" },
  { id: "your", unit: "people", en: "your", ja: "あなたの", exampleEn: "What's your name?", exampleJa: "あなたの名前は？" },
  { id: "yours", unit: "people", en: "yours", ja: "あなたのもの", exampleEn: "Is this yours?", exampleJa: "これはあなたのもの？" },
  { id: "he", unit: "people", en: "he", ja: "彼は", exampleEn: "He is a teacher.", exampleJa: "彼は先生です。" },
  { id: "his", unit: "people", en: "his", ja: "彼の", exampleEn: "This is his pen.", exampleJa: "これは彼のペンです。" },
  { id: "him", unit: "people", en: "him", ja: "彼を・彼に", exampleEn: "I like him.", exampleJa: "彼が好きです。" },
  { id: "she", unit: "people", en: "she", ja: "彼女は", exampleEn: "She is happy.", exampleJa: "彼女はうれしそうです。" },
  { id: "her", unit: "people", en: "her", ja: "彼女の・彼女を", exampleEn: "This is her desk.", exampleJa: "これは彼女の机です。" },
  { id: "we", unit: "people", en: "we", ja: "私たちは", exampleEn: "We are students.", exampleJa: "私たちは生徒です。" },
  { id: "our", unit: "people", en: "our", ja: "私たちの", exampleEn: "This is our classroom.", exampleJa: "これが私たちの教室です。" },
  { id: "us", unit: "people", en: "us", ja: "私たちを", exampleEn: "Come with us.", exampleJa: "いっしょに来て。" },
  { id: "they", unit: "people", en: "they", ja: "彼らは", exampleEn: "They are friends.", exampleJa: "彼らは友だちです。" },
  { id: "their", unit: "people", en: "their", ja: "彼らの", exampleEn: "This is their ball.", exampleJa: "これは彼らのボールです。" },
  { id: "them", unit: "people", en: "them", ja: "彼らを", exampleEn: "I know them.", exampleJa: "彼らのことを知っています。" },
  { id: "it", unit: "people", en: "it", ja: "それ・それは", exampleEn: "It is a pen.", exampleJa: "それはペンです。" },
  { id: "its", unit: "people", en: "its", ja: "それの", exampleEn: "What is its name?", exampleJa: "その名前は何？" },

  // 学校と教科
  { id: "school", unit: "school", en: "school", ja: "学校", exampleEn: "I like school.", exampleJa: "学校が好きです。" },
  { id: "student", unit: "school", en: "student", ja: "生徒", exampleEn: "I am a student.", exampleJa: "私は生徒です。" },
  { id: "teacher", unit: "school", en: "teacher", ja: "先生", exampleEn: "Ms. Green is my teacher.", exampleJa: "グリーン先生は私の先生です。" },
  { id: "friend", unit: "school", en: "friend", ja: "友だち", exampleEn: "Ken is my friend.", exampleJa: "ケンは友だちです。" },
  { id: "classmate", unit: "school", en: "classmate", ja: "クラスメート", exampleEn: "She is my classmate.", exampleJa: "彼女はクラスメートです。" },
  { id: "class", unit: "school", en: "class", ja: "授業・クラス", exampleEn: "We have English class.", exampleJa: "英語の授業があります。" },
  { id: "classroom", unit: "school", en: "classroom", ja: "教室", exampleEn: "This is our classroom.", exampleJa: "これが私たちの教室です。" },
  { id: "name", unit: "school", en: "name", ja: "名前", exampleEn: "My name is Aki.", exampleJa: "名前はアキです。" },
  { id: "english", unit: "school", en: "English", ja: "英語", exampleEn: "I like English.", exampleJa: "英語が好きです。" },
  { id: "japanese", unit: "school", en: "Japanese", ja: "国語・日本語", exampleEn: "I study Japanese.", exampleJa: "国語を勉強します。" },
  { id: "math", unit: "school", en: "math", ja: "数学", exampleEn: "Math is fun.", exampleJa: "数学は楽しいです。" },
  { id: "science", unit: "school", en: "science", ja: "理科", exampleEn: "I like science.", exampleJa: "理科が好きです。" },
  { id: "music", unit: "school", en: "music", ja: "音楽", exampleEn: "We have music today.", exampleJa: "きょうは音楽があります。" },
  { id: "art", unit: "school", en: "art", ja: "美術", exampleEn: "Art is interesting.", exampleJa: "美術はおもしろいです。" },
  { id: "pe", unit: "school", en: "P.E.", ja: "体育", exampleEn: "I like P.E.", exampleJa: "体育が好きです。" },
  { id: "homework", unit: "school", en: "homework", ja: "宿題", exampleEn: "I have homework.", exampleJa: "宿題があります。" },
  { id: "textbook", unit: "school", en: "textbook", ja: "教科書", exampleEn: "Open your textbook.", exampleJa: "教科書を開いて。" },
  { id: "notebook", unit: "school", en: "notebook", ja: "ノート", exampleEn: "This is my notebook.", exampleJa: "これは私のノートです。" },
  { id: "pencil", unit: "school", en: "pencil", ja: "えんぴつ", exampleEn: "I have a pencil.", exampleJa: "えんぴつを持っています。" },
  { id: "pen", unit: "school", en: "pen", ja: "ペン", exampleEn: "I have a pen.", exampleJa: "ペンを持っています。" },
  { id: "eraser", unit: "school", en: "eraser", ja: "消しゴム", exampleEn: "Can I use your eraser?", exampleJa: "消しゴムを借りていい？" },
  { id: "book", unit: "school", en: "book", ja: "本", exampleEn: "This is an English book.", exampleJa: "これは英語の本です。" },
  { id: "desk", unit: "school", en: "desk", ja: "机", exampleEn: "This is my desk.", exampleJa: "これは私の机です。" },
  { id: "chair", unit: "school", en: "chair", ja: "いす", exampleEn: "Sit on the chair.", exampleJa: "いすにすわって。" },
  { id: "bag", unit: "school", en: "bag", ja: "かばん", exampleEn: "This is my bag.", exampleJa: "これは私のかばんです。" },

  // 数字と年齢
  { id: "one", unit: "numbers", en: "one", ja: "1", exampleEn: "I have one dog.", exampleJa: "犬が1びきいます。" },
  { id: "two", unit: "numbers", en: "two", ja: "2", exampleEn: "I have two cats.", exampleJa: "猫が2ひきいます。" },
  { id: "three", unit: "numbers", en: "three", ja: "3", exampleEn: "I have three pens.", exampleJa: "ペンが3本あります。" },
  { id: "four", unit: "numbers", en: "four", ja: "4", exampleEn: "We are four.", exampleJa: "4人です。" },
  { id: "five", unit: "numbers", en: "five", ja: "5", exampleEn: "I am five.", exampleJa: "5歳です。" },
  { id: "six", unit: "numbers", en: "six", ja: "6", exampleEn: "It is six o'clock.", exampleJa: "6時です。" },
  { id: "seven", unit: "numbers", en: "seven", ja: "7", exampleEn: "I have seven books.", exampleJa: "本が7冊あります。" },
  { id: "eight", unit: "numbers", en: "eight", ja: "8", exampleEn: "She is eight.", exampleJa: "彼女は8歳です。" },
  { id: "nine", unit: "numbers", en: "nine", ja: "9", exampleEn: "I have nine pencils.", exampleJa: "えんぴつが9本あります。" },
  { id: "ten", unit: "numbers", en: "ten", ja: "10", exampleEn: "Count to ten.", exampleJa: "10まで数えて。" },
  { id: "eleven", unit: "numbers", en: "eleven", ja: "11", exampleEn: "It is eleven o'clock.", exampleJa: "11時です。" },
  { id: "twelve", unit: "numbers", en: "twelve", ja: "12", exampleEn: "I am twelve.", exampleJa: "12歳です。" },
  { id: "twenty", unit: "numbers", en: "twenty", ja: "20", exampleEn: "I have twenty books.", exampleJa: "本が20冊あります。" },
  { id: "hundred", unit: "numbers", en: "hundred", ja: "100", exampleEn: "I have one hundred yen.", exampleJa: "100円持っています。" },
  { id: "years-old", unit: "numbers", en: "years old", ja: "〜歳", exampleEn: "I am twelve years old.", exampleJa: "私は12歳です。" },
  { id: "first", unit: "numbers", en: "first", ja: "1番目の", exampleEn: "I am in the first grade.", exampleJa: "1年生です。" },

  // 家族
  { id: "family", unit: "family", en: "family", ja: "家族", exampleEn: "This is my family.", exampleJa: "これが私の家族です。" },
  { id: "mother", unit: "family", en: "mother", ja: "母", exampleEn: "This is my mother.", exampleJa: "こちらは母です。" },
  { id: "father", unit: "family", en: "father", ja: "父", exampleEn: "My father is a teacher.", exampleJa: "父は先生です。" },
  { id: "brother", unit: "family", en: "brother", ja: "兄・弟", exampleEn: "I have a brother.", exampleJa: "兄（弟）がいます。" },
  { id: "sister", unit: "family", en: "sister", ja: "姉・妹", exampleEn: "This is my sister.", exampleJa: "こちらは姉（妹）です。" },
  { id: "grandmother", unit: "family", en: "grandmother", ja: "祖母", exampleEn: "My grandmother is kind.", exampleJa: "おばあちゃんはやさしいです。" },
  { id: "grandfather", unit: "family", en: "grandfather", ja: "祖父", exampleEn: "My grandfather is old.", exampleJa: "おじいちゃんは年上です。" },
  { id: "parents", unit: "family", en: "parents", ja: "両親", exampleEn: "My parents are busy.", exampleJa: "両親は忙しいです。" },
  { id: "baby", unit: "family", en: "baby", ja: "赤ちゃん", exampleEn: "The baby is cute.", exampleJa: "赤ちゃんはかわいいです。" },
  { id: "uncle", unit: "family", en: "uncle", ja: "おじ", exampleEn: "This is my uncle.", exampleJa: "こちらはおじです。" },
  { id: "aunt", unit: "family", en: "aunt", ja: "おば", exampleEn: "My aunt lives in Osaka.", exampleJa: "おばは大阪に住んでいます。" },
  { id: "cousin", unit: "family", en: "cousin", ja: "いとこ", exampleEn: "He is my cousin.", exampleJa: "彼はいとこです。" },

  // 疑問詞
  { id: "what", unit: "wh", en: "what", ja: "何", exampleEn: "What is this?", exampleJa: "これは何ですか。" },
  { id: "where", unit: "wh", en: "where", ja: "どこ", exampleEn: "Where is my book?", exampleJa: "本はどこ？" },
  { id: "when", unit: "wh", en: "when", ja: "いつ", exampleEn: "When is your birthday?", exampleJa: "誕生日はいつ？" },
  { id: "who", unit: "wh", en: "who", ja: "誰", exampleEn: "Who is he?", exampleJa: "彼は誰ですか。" },
  { id: "whose", unit: "wh", en: "whose", ja: "誰の", exampleEn: "Whose pen is this?", exampleJa: "これは誰のペン？" },
  { id: "which", unit: "wh", en: "which", ja: "どの", exampleEn: "Which do you like?", exampleJa: "どっちが好き？" },
  { id: "how", unit: "wh", en: "how", ja: "どのように", exampleEn: "How are you?", exampleJa: "げんきですか。" },
  { id: "why", unit: "wh", en: "why", ja: "なぜ", exampleEn: "Why?", exampleJa: "どうして？" },
  { id: "how-old", unit: "wh", en: "How old", ja: "何歳", exampleEn: "How old are you?", exampleJa: "何歳ですか。" },
  { id: "how-many", unit: "wh", en: "How many", ja: "いくつ・何人", exampleEn: "How many books?", exampleJa: "本は何冊？" },
  { id: "what-time", unit: "wh", en: "What time", ja: "何時", exampleEn: "What time is it?", exampleJa: "何時ですか。" },
  { id: "what-color", unit: "wh", en: "What color", ja: "何色", exampleEn: "What color is it?", exampleJa: "何色ですか。" },
  { id: "where-from", unit: "wh", en: "Where from", ja: "どこから", exampleEn: "Where are you from?", exampleJa: "出身はどこですか。" },

  // 天気と季節
  { id: "sunny", unit: "weather", en: "sunny", ja: "晴れている", exampleEn: "It's sunny today.", exampleJa: "きょうは晴れです。" },
  { id: "cloudy", unit: "weather", en: "cloudy", ja: "曇っている", exampleEn: "It's cloudy.", exampleJa: "くもりです。" },
  { id: "rainy", unit: "weather", en: "rainy", ja: "雨が降っている", exampleEn: "It's rainy today.", exampleJa: "きょうは雨です。" },
  { id: "snowy", unit: "weather", en: "snowy", ja: "雪が降っている", exampleEn: "It's snowy.", exampleJa: "雪です。" },
  { id: "windy", unit: "weather", en: "windy", ja: "風が強い", exampleEn: "It's windy today.", exampleJa: "きょうは風が強いです。" },
  { id: "hot", unit: "weather", en: "hot", ja: "暑い", exampleEn: "It's hot today.", exampleJa: "きょうは暑いです。" },
  { id: "cold", unit: "weather", en: "cold", ja: "寒い", exampleEn: "It's cold.", exampleJa: "寒いです。" },
  { id: "warm", unit: "weather", en: "warm", ja: "暖かい", exampleEn: "It's warm in spring.", exampleJa: "春は暖かいです。" },
  { id: "cool", unit: "weather", en: "cool", ja: "涼しい", exampleEn: "It's cool in the morning.", exampleJa: "朝は涼しいです。" },
  { id: "weather", unit: "weather", en: "weather", ja: "天気", exampleEn: "How's the weather?", exampleJa: "天気はどう？" },
  { id: "spring", unit: "weather", en: "spring", ja: "春", exampleEn: "I like spring.", exampleJa: "春が好きです。" },
  { id: "summer", unit: "weather", en: "summer", ja: "夏", exampleEn: "Summer is hot.", exampleJa: "夏は暑いです。" },
  { id: "fall", unit: "weather", en: "fall", ja: "秋", exampleEn: "Fall is nice.", exampleJa: "秋は気持ちいいです。" },
  { id: "winter", unit: "weather", en: "winter", ja: "冬", exampleEn: "Winter is cold.", exampleJa: "冬は寒いです。" },

  // 気分とようす
  { id: "happy", unit: "feelings", en: "happy", ja: "うれしい", exampleEn: "I am happy.", exampleJa: "うれしいです。" },
  { id: "sad", unit: "feelings", en: "sad", ja: "悲しい", exampleEn: "She is sad.", exampleJa: "彼女は悲しそうです。" },
  { id: "hungry", unit: "feelings", en: "hungry", ja: "おなかがすいた", exampleEn: "I am hungry.", exampleJa: "おなかがすきました。" },
  { id: "thirsty", unit: "feelings", en: "thirsty", ja: "のどがかわいた", exampleEn: "I am thirsty.", exampleJa: "のどがかわきました。" },
  { id: "tired", unit: "feelings", en: "tired", ja: "疲れた", exampleEn: "I am tired.", exampleJa: "疲れました。" },
  { id: "sleepy", unit: "feelings", en: "sleepy", ja: "眠い", exampleEn: "I am sleepy.", exampleJa: "眠いです。" },
  { id: "busy", unit: "feelings", en: "busy", ja: "忙しい", exampleEn: "I am busy today.", exampleJa: "きょうは忙しいです。" },
  { id: "sick", unit: "feelings", en: "sick", ja: "病気の・具合が悪い", exampleEn: "He is sick.", exampleJa: "彼は具合が悪いです。" },
  { id: "great", unit: "feelings", en: "great", ja: "すばらしい・元気な", exampleEn: "That's great!", exampleJa: "すごいね！" },
  { id: "good", unit: "feelings", en: "good", ja: "よい", exampleEn: "This is good.", exampleJa: "これはよいです。" },

  // 身のまわり
  { id: "this", unit: "around", en: "this", ja: "これ", exampleEn: "This is a book.", exampleJa: "これは本です。" },
  { id: "that", unit: "around", en: "that", ja: "あれ", exampleEn: "That is a pen.", exampleJa: "あれはペンです。" },
  { id: "these", unit: "around", en: "these", ja: "これら", exampleEn: "These are my books.", exampleJa: "これらは私の本です。" },
  { id: "those", unit: "around", en: "those", ja: "あれら", exampleEn: "Those are dogs.", exampleJa: "あれらは犬です。" },
  { id: "here", unit: "around", en: "here", ja: "ここ", exampleEn: "Come here.", exampleJa: "ここに来て。" },
  { id: "there", unit: "around", en: "there", ja: "あそこ・そこに", exampleEn: "Look over there.", exampleJa: "あそこを見て。" },
  { id: "house", unit: "around", en: "house", ja: "家", exampleEn: "This is my house.", exampleJa: "これがうちです。" },
  { id: "home", unit: "around", en: "home", ja: "家・自宅", exampleEn: "Let's go home.", exampleJa: "家に帰ろう。" },
  { id: "room", unit: "around", en: "room", ja: "部屋", exampleEn: "This is my room.", exampleJa: "これが私の部屋です。" },
  { id: "dog", unit: "around", en: "dog", ja: "犬", exampleEn: "I have a dog.", exampleJa: "犬を飼っています。" },
  { id: "cat", unit: "around", en: "cat", ja: "猫", exampleEn: "This is my cat.", exampleJa: "これは私の猫です。" },
  { id: "bird", unit: "around", en: "bird", ja: "鳥", exampleEn: "I see a bird.", exampleJa: "鳥が見えます。" },
  { id: "fish", unit: "around", en: "fish", ja: "魚", exampleEn: "I like fish.", exampleJa: "魚が好きです。" },
  { id: "ball", unit: "around", en: "ball", ja: "ボール", exampleEn: "This is a ball.", exampleJa: "これはボールです。" },
  { id: "phone", unit: "around", en: "phone", ja: "電話", exampleEn: "This is my phone.", exampleJa: "これは私の電話です。" },

  // 色
  { id: "red", unit: "colors", en: "red", ja: "赤い", exampleEn: "I like red.", exampleJa: "赤が好きです。" },
  { id: "blue", unit: "colors", en: "blue", ja: "青い", exampleEn: "The sky is blue.", exampleJa: "空は青いです。" },
  { id: "yellow", unit: "colors", en: "yellow", ja: "黄色い", exampleEn: "This is yellow.", exampleJa: "これは黄色です。" },
  { id: "green", unit: "colors", en: "green", ja: "緑の", exampleEn: "The tree is green.", exampleJa: "木は緑です。" },
  { id: "white", unit: "colors", en: "white", ja: "白い", exampleEn: "I have a white cat.", exampleJa: "白い猫がいます。" },
  { id: "black", unit: "colors", en: "black", ja: "黒い", exampleEn: "I like black.", exampleJa: "黒が好きです。" },
  { id: "orange-color", unit: "colors", en: "orange", ja: "オレンジ色の", exampleEn: "This is orange.", exampleJa: "これはオレンジ色です。" },
  { id: "pink", unit: "colors", en: "pink", ja: "ピンクの", exampleEn: "I like pink.", exampleJa: "ピンクが好きです。" },
  { id: "brown", unit: "colors", en: "brown", ja: "茶色の", exampleEn: "The dog is brown.", exampleJa: "その犬は茶色です。" },
  { id: "purple", unit: "colors", en: "purple", ja: "むらさきの", exampleEn: "This is purple.", exampleJa: "これはむらさきです。" },

  // 食べ物
  { id: "food", unit: "food", en: "food", ja: "食べ物", exampleEn: "The food is good.", exampleJa: "食べ物がおいしいです。" },
  { id: "apple", unit: "food", en: "apple", ja: "りんご", exampleEn: "I like apples.", exampleJa: "りんごが好きです。" },
  { id: "orange-fruit", unit: "food", en: "orange", ja: "オレンジ", exampleEn: "I eat an orange.", exampleJa: "オレンジを食べます。" },
  { id: "banana", unit: "food", en: "banana", ja: "バナナ", exampleEn: "I like bananas.", exampleJa: "バナナが好きです。" },
  { id: "bread", unit: "food", en: "bread", ja: "パン", exampleEn: "I eat bread.", exampleJa: "パンを食べます。" },
  { id: "rice", unit: "food", en: "rice", ja: "ごはん", exampleEn: "I like rice.", exampleJa: "ごはんが好きです。" },
  { id: "egg", unit: "food", en: "egg", ja: "卵", exampleEn: "I eat an egg.", exampleJa: "卵を食べます。" },
  { id: "milk", unit: "food", en: "milk", ja: "牛乳", exampleEn: "I drink milk.", exampleJa: "牛乳を飲みます。" },
  { id: "water", unit: "food", en: "water", ja: "水", exampleEn: "I want water.", exampleJa: "水がほしいです。" },
  { id: "juice", unit: "food", en: "juice", ja: "ジュース", exampleEn: "I like juice.", exampleJa: "ジュースが好きです。" },
  { id: "tea", unit: "food", en: "tea", ja: "お茶", exampleEn: "I drink tea.", exampleJa: "お茶を飲みます。" },
  { id: "coffee", unit: "food", en: "coffee", ja: "コーヒー", exampleEn: "My father likes coffee.", exampleJa: "父はコーヒーが好きです。" },
  { id: "meat", unit: "food", en: "meat", ja: "肉", exampleEn: "I eat meat.", exampleJa: "肉を食べます。" },
  { id: "cake", unit: "food", en: "cake", ja: "ケーキ", exampleEn: "I like cake.", exampleJa: "ケーキが好きです。" },
  { id: "ice-cream", unit: "food", en: "ice cream", ja: "アイスクリーム", exampleEn: "I want ice cream.", exampleJa: "アイスクリームがほしいです。" },
  { id: "breakfast", unit: "food", en: "breakfast", ja: "朝ごはん", exampleEn: "I eat breakfast.", exampleJa: "朝ごはんを食べます。" },
  { id: "lunch", unit: "food", en: "lunch", ja: "昼ごはん", exampleEn: "Let's eat lunch.", exampleJa: "昼ごはんを食べよう。" },
  { id: "dinner", unit: "food", en: "dinner", ja: "夜ごはん", exampleEn: "Dinner is at six.", exampleJa: "夜ごはんは6時です。" },

  // スポーツ
  { id: "sport", unit: "sports", en: "sport", ja: "スポーツ", exampleEn: "What sport do you like?", exampleJa: "何のスポーツが好き？" },
  { id: "soccer", unit: "sports", en: "soccer", ja: "サッカー", exampleEn: "I play soccer.", exampleJa: "サッカーをします。" },
  { id: "baseball", unit: "sports", en: "baseball", ja: "野球", exampleEn: "I like baseball.", exampleJa: "野球が好きです。" },
  { id: "basketball", unit: "sports", en: "basketball", ja: "バスケットボール", exampleEn: "We play basketball.", exampleJa: "バスケをします。" },
  { id: "tennis", unit: "sports", en: "tennis", ja: "テニス", exampleEn: "She plays tennis.", exampleJa: "彼女はテニスをします。" },
  { id: "volleyball", unit: "sports", en: "volleyball", ja: "バレーボール", exampleEn: "I like volleyball.", exampleJa: "バレーが好きです。" },
  { id: "swimming", unit: "sports", en: "swimming", ja: "水泳", exampleEn: "Swimming is fun.", exampleJa: "水泳は楽しいです。" },
  { id: "table-tennis", unit: "sports", en: "table tennis", ja: "卓球", exampleEn: "I play table tennis.", exampleJa: "卓球をします。" },
  { id: "run", unit: "sports", en: "run", ja: "走る", exampleEn: "I run in the park.", exampleJa: "公園で走ります。" },
  { id: "walk", unit: "sports", en: "walk", ja: "歩く", exampleEn: "I walk to school.", exampleJa: "歩いて学校へ行きます。" },

  // 動作
  { id: "like", unit: "actions", en: "like", ja: "好きである", exampleEn: "I like English.", exampleJa: "英語が好きです。" },
  { id: "love", unit: "actions", en: "love", ja: "とても好き・愛する", exampleEn: "I love soccer.", exampleJa: "サッカーが大好きです。" },
  { id: "have", unit: "actions", en: "have", ja: "持っている", exampleEn: "I have a pen.", exampleJa: "ペンを持っています。" },
  { id: "play", unit: "actions", en: "play", ja: "遊ぶ・演奏する", exampleEn: "I play soccer.", exampleJa: "サッカーをします。" },
  { id: "go", unit: "actions", en: "go", ja: "行く", exampleEn: "I go to school.", exampleJa: "学校へ行きます。" },
  { id: "come", unit: "actions", en: "come", ja: "来る", exampleEn: "Come here.", exampleJa: "ここに来て。" },
  { id: "study", unit: "actions", en: "study", ja: "勉強する", exampleEn: "I study English.", exampleJa: "英語を勉強します。" },
  { id: "watch", unit: "actions", en: "watch", ja: "見る（テレビなど）", exampleEn: "I watch TV.", exampleJa: "テレビを見ます。" },
  { id: "listen", unit: "actions", en: "listen", ja: "聞く", exampleEn: "Listen to me.", exampleJa: "私の話を聞いて。" },
  { id: "speak", unit: "actions", en: "speak", ja: "話す", exampleEn: "I speak English.", exampleJa: "英語を話します。" },
  { id: "read", unit: "actions", en: "read", ja: "読む", exampleEn: "I read a book.", exampleJa: "本を読みます。" },
  { id: "write", unit: "actions", en: "write", ja: "書く", exampleEn: "Write your name.", exampleJa: "名前を書いて。" },
  { id: "eat", unit: "actions", en: "eat", ja: "食べる", exampleEn: "I eat bread.", exampleJa: "パンを食べます。" },
  { id: "drink", unit: "actions", en: "drink", ja: "飲む", exampleEn: "I drink water.", exampleJa: "水を飲みます。" },
  { id: "want", unit: "actions", en: "want", ja: "ほしい・したい", exampleEn: "I want a pen.", exampleJa: "ペンがほしいです。" },
  { id: "live", unit: "actions", en: "live", ja: "住む", exampleEn: "I live in Tokyo.", exampleJa: "東京に住んでいます。" },
  { id: "know", unit: "actions", en: "know", ja: "知っている", exampleEn: "I know him.", exampleJa: "彼を知っています。" },
  { id: "help", unit: "actions", en: "help", ja: "助ける", exampleEn: "Please help me.", exampleJa: "助けてください。" },
  { id: "look", unit: "actions", en: "look", ja: "見る・見える", exampleEn: "Look at this.", exampleJa: "これを見て。" },
  { id: "make", unit: "actions", en: "make", ja: "作る", exampleEn: "I make a cake.", exampleJa: "ケーキを作ります。" },

  // できること
  { id: "can", unit: "can", en: "can", ja: "できる", exampleEn: "I can swim.", exampleJa: "泳げます。" },
  { id: "cant", unit: "can", en: "can't", ja: "できない", exampleEn: "I can't cook.", exampleJa: "料理はできません。" },
  { id: "swim", unit: "can", en: "swim", ja: "泳ぐ", exampleEn: "I can swim.", exampleJa: "泳げます。" },
  { id: "cook", unit: "can", en: "cook", ja: "料理する", exampleEn: "I can cook.", exampleJa: "料理ができます。" },
  { id: "sing", unit: "can", en: "sing", ja: "歌う", exampleEn: "She can sing.", exampleJa: "彼女は歌えます。" },
  { id: "dance", unit: "can", en: "dance", ja: "踊る", exampleEn: "I can dance.", exampleJa: "踊れます。" },
  { id: "piano", unit: "can", en: "piano", ja: "ピアノ", exampleEn: "I can play the piano.", exampleJa: "ピアノが弾けます。" },
  { id: "guitar", unit: "can", en: "guitar", ja: "ギター", exampleEn: "He can play the guitar.", exampleJa: "彼はギターが弾けます。" },
  { id: "skate", unit: "can", en: "skate", ja: "スケートをする", exampleEn: "I can skate.", exampleJa: "スケートができます。" },
  { id: "ski", unit: "can", en: "ski", ja: "スキーをする", exampleEn: "I can ski.", exampleJa: "スキーができます。" },
  { id: "well", unit: "can", en: "well", ja: "上手に", exampleEn: "She can sing well.", exampleJa: "彼女は歌うのが上手です。" },
  { id: "a-little", unit: "can", en: "a little", ja: "少し", exampleEn: "I can speak English a little.", exampleJa: "英語を少し話せます。" },

  // 曜日と時間
  { id: "sunday", unit: "time", en: "Sunday", ja: "日曜日", exampleEn: "It's Sunday today.", exampleJa: "きょうは日曜日です。" },
  { id: "monday", unit: "time", en: "Monday", ja: "月曜日", exampleEn: "I go to school on Monday.", exampleJa: "月曜日に学校へ行きます。" },
  { id: "tuesday", unit: "time", en: "Tuesday", ja: "火曜日", exampleEn: "We have music on Tuesday.", exampleJa: "火曜日は音楽があります。" },
  { id: "wednesday", unit: "time", en: "Wednesday", ja: "水曜日", exampleEn: "It's Wednesday.", exampleJa: "水曜日です。" },
  { id: "thursday", unit: "time", en: "Thursday", ja: "木曜日", exampleEn: "I play soccer on Thursday.", exampleJa: "木曜日にサッカーをします。" },
  { id: "friday", unit: "time", en: "Friday", ja: "金曜日", exampleEn: "Friday is fun.", exampleJa: "金曜日は楽しいです。" },
  { id: "saturday", unit: "time", en: "Saturday", ja: "土曜日", exampleEn: "I stay home on Saturday.", exampleJa: "土曜日は家にいます。" },
  { id: "today", unit: "time", en: "today", ja: "きょう", exampleEn: "I am busy today.", exampleJa: "きょうは忙しいです。" },
  { id: "tomorrow", unit: "time", en: "tomorrow", ja: "あした", exampleEn: "See you tomorrow.", exampleJa: "またあした。" },
  { id: "yesterday", unit: "time", en: "yesterday", ja: "きのう", exampleEn: "I was busy yesterday.", exampleJa: "きのうは忙しかったです。" },
  { id: "morning", unit: "time", en: "morning", ja: "朝", exampleEn: "I eat breakfast in the morning.", exampleJa: "朝ごはんを食べます。" },
  { id: "afternoon", unit: "time", en: "afternoon", ja: "午後", exampleEn: "I study in the afternoon.", exampleJa: "午後に勉強します。" },
  { id: "evening", unit: "time", en: "evening", ja: "夕方・晩", exampleEn: "Good evening.", exampleJa: "こんばんは。" },
  { id: "night", unit: "time", en: "night", ja: "夜", exampleEn: "Good night.", exampleJa: "おやすみなさい。" },
  { id: "now", unit: "time", en: "now", ja: "今", exampleEn: "I am busy now.", exampleJa: "今は忙しいです。" },
  { id: "oclock", unit: "time", en: "o'clock", ja: "〜時", exampleEn: "It's seven o'clock.", exampleJa: "7時です。" },
  { id: "week", unit: "time", en: "week", ja: "週", exampleEn: "I play soccer every week.", exampleJa: "毎週サッカーをします。" },
  { id: "year", unit: "time", en: "year", ja: "年", exampleEn: "I am twelve this year.", exampleJa: "今年12歳です。" },
  { id: "birthday", unit: "time", en: "birthday", ja: "誕生日", exampleEn: "When is your birthday?", exampleJa: "誕生日はいつ？" },

  // 月
  { id: "january", unit: "months", en: "January", ja: "1月", exampleEn: "My birthday is in January.", exampleJa: "誕生日は1月です。" },
  { id: "february", unit: "months", en: "February", ja: "2月", exampleEn: "It's cold in February.", exampleJa: "2月は寒いです。" },
  { id: "march", unit: "months", en: "March", ja: "3月", exampleEn: "Spring comes in March.", exampleJa: "3月に春が来ます。" },
  { id: "april", unit: "months", en: "April", ja: "4月", exampleEn: "School starts in April.", exampleJa: "4月に学校が始まります。" },
  { id: "may", unit: "months", en: "May", ja: "5月", exampleEn: "I like May.", exampleJa: "5月が好きです。" },
  { id: "june", unit: "months", en: "June", ja: "6月", exampleEn: "It's rainy in June.", exampleJa: "6月は雨が多いです。" },
  { id: "july", unit: "months", en: "July", ja: "7月", exampleEn: "Summer vacation is in July.", exampleJa: "夏休みは7月です。" },
  { id: "august", unit: "months", en: "August", ja: "8月", exampleEn: "August is hot.", exampleJa: "8月は暑いです。" },
  { id: "september", unit: "months", en: "September", ja: "9月", exampleEn: "School starts in September.", exampleJa: "9月に学校が始まります。" },
  { id: "october", unit: "months", en: "October", ja: "10月", exampleEn: "I like October.", exampleJa: "10月が好きです。" },
  { id: "november", unit: "months", en: "November", ja: "11月", exampleEn: "It's cool in November.", exampleJa: "11月は涼しいです。" },
  { id: "december", unit: "months", en: "December", ja: "12月", exampleEn: "December is cold.", exampleJa: "12月は寒いです。" },

  // 場所
  { id: "park", unit: "places", en: "park", ja: "公園", exampleEn: "I play in the park.", exampleJa: "公園で遊びます。" },
  { id: "station", unit: "places", en: "station", ja: "駅", exampleEn: "Let's go to the station.", exampleJa: "駅へ行こう。" },
  { id: "library", unit: "places", en: "library", ja: "図書館", exampleEn: "I study in the library.", exampleJa: "図書館で勉強します。" },
  { id: "hospital", unit: "places", en: "hospital", ja: "病院", exampleEn: "He is in the hospital.", exampleJa: "彼は病院にいます。" },
  { id: "store", unit: "places", en: "store", ja: "店", exampleEn: "I go to the store.", exampleJa: "店へ行きます。" },
  { id: "restaurant", unit: "places", en: "restaurant", ja: "レストラン", exampleEn: "Let's eat at a restaurant.", exampleJa: "レストランで食べよう。" },
  { id: "zoo", unit: "places", en: "zoo", ja: "動物園", exampleEn: "I like the zoo.", exampleJa: "動物園が好きです。" },
  { id: "japan", unit: "places", en: "Japan", ja: "日本", exampleEn: "I live in Japan.", exampleJa: "日本に住んでいます。" },
  { id: "america", unit: "places", en: "America", ja: "アメリカ", exampleEn: "She is from America.", exampleJa: "彼女はアメリカ出身です。" },
  { id: "tokyo", unit: "places", en: "Tokyo", ja: "東京", exampleEn: "I live in Tokyo.", exampleJa: "東京に住んでいます。" },
  { id: "city", unit: "places", en: "city", ja: "市・街", exampleEn: "This is a big city.", exampleJa: "大きな街です。" },
  { id: "country", unit: "places", en: "country", ja: "国", exampleEn: "What country are you from?", exampleJa: "どの国の出身ですか。" },

  // 形容詞
  { id: "big", unit: "adjectives", en: "big", ja: "大きい", exampleEn: "This is a big dog.", exampleJa: "大きな犬です。" },
  { id: "small", unit: "adjectives", en: "small", ja: "小さい", exampleEn: "I have a small cat.", exampleJa: "小さい猫がいます。" },
  { id: "new", unit: "adjectives", en: "new", ja: "新しい", exampleEn: "This is a new bag.", exampleJa: "新しいかばんです。" },
  { id: "old", unit: "adjectives", en: "old", ja: "古い・年をとった", exampleEn: "This is an old book.", exampleJa: "古い本です。" },
  { id: "nice", unit: "adjectives", en: "nice", ja: "すてきな・よい", exampleEn: "It's a nice day.", exampleJa: "いい天気です。" },
  { id: "kind", unit: "adjectives", en: "kind", ja: "やさしい", exampleEn: "She is kind.", exampleJa: "彼女はやさしいです。" },
  { id: "long", unit: "adjectives", en: "long", ja: "長い", exampleEn: "I have long hair.", exampleJa: "髪が長いです。" },
  { id: "short", unit: "adjectives", en: "short", ja: "短い", exampleEn: "This is a short pencil.", exampleJa: "短いえんぴつです。" },
  { id: "tall", unit: "adjectives", en: "tall", ja: "背が高い", exampleEn: "He is tall.", exampleJa: "彼は背が高いです。" },
  { id: "young", unit: "adjectives", en: "young", ja: "若い", exampleEn: "She is young.", exampleJa: "彼女は若いです。" },
  { id: "favorite", unit: "adjectives", en: "favorite", ja: "いちばん好きな", exampleEn: "Soccer is my favorite sport.", exampleJa: "サッカーがいちばん好きです。" },
  { id: "fun", unit: "adjectives", en: "fun", ja: "楽しい", exampleEn: "English is fun.", exampleJa: "英語は楽しいです。" },
  { id: "interesting", unit: "adjectives", en: "interesting", ja: "おもしろい", exampleEn: "This book is interesting.", exampleJa: "この本はおもしろいです。" },
  { id: "easy", unit: "adjectives", en: "easy", ja: "簡単な", exampleEn: "This is easy.", exampleJa: "これは簡単です。" },
  { id: "difficult", unit: "adjectives", en: "difficult", ja: "難しい", exampleEn: "Math is difficult.", exampleJa: "数学は難しいです。" },
  { id: "cute", unit: "adjectives", en: "cute", ja: "かわいい", exampleEn: "The cat is cute.", exampleJa: "その猫はかわいいです。" },
];

const ONBOARD_IDS = ["hello", "thank-you", "dog"];
const SESSION_SIZE = 8;
const MASTER_BOX = 2;
const INTERVAL_DAYS = { 1: 1, 2: 3, 3: 7 };
